### ISSUE TITLE
Specify the DSL to use for Ion 1.1 test vectors

### ISSUE THREAD

**Issue by tgregg** [amazon-ion/ion-tests#87]

**Comment by toddjonker** [comment]
See #89

**Comment by toddjonker** [comment]
Can I get access to this repository?  I believe this issue is complete per #89 but I can't close the issue.

**Comment by tgregg** [comment]
@toddjonker You should have access now. Can you try again?

**Comment by toddjonker** [comment]
@tgregg That worked, thanks!
