### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by toddjonker** [amazon-ion/ion-tests#90]
I'd like to rename `master` to `main` to align with modern best practices.

This will have some impact on developer's cloned repositories.  The renaming dialog says:

> Your members will have to manually update their local environments. We'll let them know when they visit the repository, or you can share the following commands.

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

It looks like GitHub handle renaming pretty well in terms of pull requests, existing links, and so on; see https://github.com/github/renaming

**Comment by zslayton** [comment]
Done!
